name: Display secret

on: [push]

jobs:
  display-secret:
    runs-on: ubuntu-latest
    env:
      GLOBAL_VAR: "Helloworld"
    steps:
      - name: Use global var
        run: echo "Global says: $GLOBAL_VAR"
