name: Display secret

on: [push]

jobs:
  display-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Display secret (masked) 
        env:
          TOKEN: ${{ secrets.FAKE_API_TOKEN }}
        run: |
          echo "Token starts with ${TOKEN::5}..."
